version: '3.7'
name: news-signal-historical
networks:
  redpanda_network:
    external: true
    name: redpanda_network
services:
  news:
    build:
      context: ../services/news
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_TOPIC=news_historical_${RUN_ID}
      - DATA_SOURCE=historical
      - HISTORICAL_DATA_SOURCE_CSV_FILE=/app/data/cryptopanic_news.csv
    volumes:
      - ../services/news/data:/app/data


  news-signal:
    build:
      context: ../services/news-signal
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_INPUT_TOPIC=news_historical_${RUN_ID}
      - KAFKA_OUTPUT_TOPIC=news_signal_historical_${RUN_ID}
      - KAFKA_CONSUMER_GROUP=news_signal_historical_${RUN_ID}
      - MODEL_PROVIDER=dummy # TODO: change to our fine tuned model (once we manage to export it!)
      - DATA_SOURCE=historical
      # - OLLAMA_BASE_URL=http://192.168.1.3:11434/ # TODO: change to docker.host.internal:11434
    restart: always

  to-feature-store:
    build:
      context: ../services/to-feature-store
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/to-feature-store/hopsworks_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_INPUT_TOPIC=news_signal_historical_${RUN_ID}
      - KAFKA_CONSUMER_GROUP=to_feature_store_news_signal_historical_${RUN_ID}
      - FEATURE_GROUP_NAME=news_signals
      - FEATURE_GROUP_VERSION=2
      - FEATURE_GROUP_PRIMARY_KEYS=["coin"]
      - FEATURE_GROUP_EVENT_TIME=timestamp_ms
      - DATA_SOURCE=historical
    restart: always
